# Generated by Django 3.1.3 on 2020-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_auto_20201212_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artiste_name',
            field=models.CharField(max_length=200),
        ),
    ]
