# Generated by Django 3.1.3 on 2020-12-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0007_auto_20201212_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_songs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_that_liked_me', to='comparison.song'),
        ),
    ]
