# Generated by Django 3.1.3 on 2020-12-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0008_auto_20201216_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_songs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(default=None, null=True, related_name='users_that_liked_me', to='comparison.Song'),
        ),
    ]
