# Generated by Django 3.1.3 on 2020-12-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0013_auto_20201229_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(default=None, null=True, related_name='users_that_liked_me', to='comparison.Song'),
        ),
    ]
