# Generated by Django 3.1.3 on 2020-12-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0014_userprofile_liked_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='comparison.userprofile')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='comparison.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='comparison.Relationship', to='comparison.UserProfile'),
        ),
    ]
