# Generated by Django 3.1.3 on 2020-12-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0015_auto_20201230_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(default=None, related_name='users_that_liked_me', to='comparison.Song'),
        ),
    ]
